External Initiator for Klaytn
smartcontractkit/external-initiator pull request #92
Opened 2021-02-08 08:14 UTC by winnie-byun

External Initiator for Klaytn.

`subscribe` API in Klaytn works similar with eth's. It is different from eth that klaytn uses 'klay' instead of 'eth' in method.
If you are subscribing something other than Log, it could have different struct from eth's. (e.g. Structs such as Headers are different.)

I've tested Klaytn EI with chainlink node and  attaching to Klaytn testnet (Baobab).

2021-04-12 19:55 UTC, aalu1418 commented
@winnie-byun Hello! I've been assigned to review the Klatyn EI implementation. After a first look, here's some feedback so we can get your PR merged!

* It seems like you based the `klatyn.go` file from the `eth.go` file which is a good start. There are some functions in creating the filter query and parsing the event logs that would be needed to make it work with our on-chain smart contracts (example from the BSC initiator).
  * Creating the filter query: https://github.com/smartcontractkit/external-initiator/blob/master/blockchain/binance-smart-chain.go#L27
  * Parsing: https://github.com/smartcontractkit/external-initiator/blob/master/blockchain/binance-smart-chain.go#L133
* Make sure all the integration tests run successfully. They can be run with instructions in the root readme
* There also seems to be some linting errors, these can usually be solved with `go fmt`
* Also, please rebase so the latest changes are included

Thanks!

2021-04-28 03:21 UTC, winnie-byun commented
@aalu1418 I changed the code like the BSC initiator and rebased.
The code is already `go fmt`ed.
I tested that with a chainlink core and it runs with no error. I will update after I tested with klaytn chainlink adapter.
Please take a look.

2021-05-12 20:09 UTC, aalu1418 requested changes
Looking pretty good!
Most of the feedback is around some missing pieces that I noticed.

2021-05-12 20:09 UTC, aalu1418 commented on integration/mock-client/blockchain/klaytn_test.go
> +}
Please add testing functions for `klaytnLogRequestToResponse` and `handleKlaytnGetLogs` 😄

2021-05-12 20:09 UTC, aalu1418 commented on blockchain/klaytn.go
> +}
Seems like you're missing the `blockchain/klaytn_test.go` file for testing the various functions?

2021-05-13 13:05 UTC, aalu1418 commented
Requested changes will be addressed in a separate PR

2021-05-13 13:05 UTC, merged